### ISSUE TITLE
Research elements of spotify api

### ISSUE THREAD

**Issue by SMLM42** [luvkylo/signed#2]

**Comment by taydougherty** [comment]
// properties needed from spotify api: 
// artist object: followers, external_urls, name, id, image, genre (https://api.spotify.com/v1/artists)
// playlist object: name, tracks (https://api.spotify.com/v1/tracks)

// spotify chart is called: Viral 50 and filters by country, frequency and latest day made

// can't sell app without explicit license
// Client ID 46c024e5c1584960ae72985029a84c82
// The base address of Web API is https://api.spotify.com

**Comment by taydougherty** [comment]
New client key for fake email: Client ID ce01ac1e69164952b0ee29ea90b860b6
