### ISSUE TITLE
Map quest api research

### ISSUE THREAD

**Issue by SMLM42** [luvkylo/signed#5]

**Comment by Dangggchris** [comment]
* We will be switching to GEO-Names API to grab country name
// get the user’s longitude and latitude. Prompt at very beginning. Default to 
var x = document.getElementById("demo");
function getLocation() {
  if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(showPosition);
  } else {
    x.innerHTML = "Geolocation is not supported by this browser.";
  }
}

function showPosition(position) {
  x.innerHTML = "Latitude: " + position.coords.latitude + 
  "<br>Longitude: " + position.coords.longitude; 
}

var lat = position.coords.latitude;
Var long = position.coords.longitude;

// concatenate key and long/lat as string into GET URL
queryURL = "api.geonames.org/countryCodeJSON?lat=" + [LATITUDE] + "&lng=" + [LONGITUDE] = "&username=[dangggchris]"

// Ajax call to API
    $.ajax({
      url: queryURL,
      method: "GET"
    }).then(function(response) {
 var countryName = response;
    });
