### ISSUE TITLE
research wikipedia api again

### ISSUE THREAD

**Issue by SMLM42** [luvkylo/signed#85]
It sucked the first time but it's the only option now so I'll look it over again.

**Comment by SMLM42** [comment]
Apparently not even the major musical artists will always have the sub topic "recording label", for instance Adele doesn't. I don't know if dbpedia is reliable enough.  For Adele, she has a "subject" XL recording artist and Columbia records artist(XL/Columbia records are recording labels). So we could add a backup to the basic call utilizing that information somehow? Bottom line is I would like to have some obscure artists to test. Also, would like to research any other possibilities of finding out whether someone is signed to a record label.

**Comment by TomSlemenson** [comment]
Spotify actually gives label information so the Wikipedia API won't be necessary.
